FROM ubuntu:22.04

LABEL maintainer="zeamort@gmail.com"

RUN apt-get update -y && apt-get install -y python3 python3-pip

# We copy just the requirements.txt first to leverage Docker cache
COPY ./requirements.txt /app/requirements.txt

WORKDIR /app

RUN pip3 install -r requirements.txt

COPY . /app

# RUN python3 create_tables.py

ENTRYPOINT [ "python3" ]

CMD [ "app.py" ]
